apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apprise.fullname" . }}
  labels:
    {{- include "apprise.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apprise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apprise.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.apprise.args }}
          args:
            {{- toYaml .Values.apprise.args | nindent 12 }}
          {{- end }}
          {{- if .Values.apprise.env }}
          env:
            {{- toYaml .Values.apprise.env | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.apprise.persistence.enabled (not (empty .Values.apprise.configFiles)) }}
          volumeMounts:
            {{- if .Values.apprise.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
            {{- if not (empty .Values.apprise.configFiles) }}
            - name: config
              mountPath: /config
            {{- end }}
          {{- end }}
      {{- if or .Values.apprise.persistence.enabled (not (empty .Values.apprise.configFiles)) }}
      volumes:
        {{- if .Values.apprise.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "apprise.fullname" . }}
        {{- end }}
        {{- if not (empty .Values.apprise.configFiles) }}
        - name: config
          configMap:
            name: {{ include "apprise.fullname" . }}-config
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}