# Minimal configuration for Apprise
replicaCount: 1

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

apprise:
  args:
    - "--help"  # Replace with actual arguments needed for your use case